### ISSUE TITLE
useBreakpoint hook does not work without snipe

### ISSUE THREAD

**Issue by ste-vg** [wethegit/corgi#103]
The breakpoint snipe component is missing and is required for the useBreakpoint hook to work.

**Comment by andrewrubin** [comment]
For whomever takes this, here's an implementation of `<BreakpointSnipe>` that you might be able to use 

https://github.com/wethegit/noa-microsite/tree/dev/src/components/app/page/components/breakpoint-snipe

Could even add this to the component library…

**Comment by ste-vg** [comment]
You'll also need to define `BREAKPOINT_SNIPE_CLASSNAME` in the `utilities/consts.js` file

**Comment by andrewrubin** [comment]
Closing in favor of the new version which lives in @wethegit/component-library

https://wethegit.github.io/component-library/?path=/docs/components-breakpoint-snipe-readme--overview

**Comment by andrewrubin** [comment]
I should mention that we have yet to port over the hook to the component library — so that's now a new issue 🙃
