### ISSUE TITLE
RFC: adding locale setup on new locales

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/corgi#55]
Would like to get some discussion going on a new feature — I am not sure if it's necessary though.

### the issue
Creating a page with any **new** locales requires extra setup in the locale config and the YAML globals. For example, running `corgi page MyAwesomePage --locales cs-CZ` on a fresh project requires extra setup for the page to work (unless you already have a Czech locale setup, in this example).

### the question
Are we bothered by this? Typically you bootstrap a project with all locales and configs you need, but maybe automated locale setup should be a feature.

**Comment by marlonmarcello** [comment]
I like this. I am all for automation, the less we need to think and configure things manually, and potentially foget to, the better.

**Comment by rvno** [comment]
In.

Think it'd be particularly useful to have a command that can include/exclude/omit which locales are being built as well. For both DPR sites I manually moved locales into a tmp folder since it was an EN 'release' first, and then had to move them all back. Had to do quite a bit of manual updating b/c I had forgotten that I moved em in the first place.and had created new versions and spent time reconciling differences.

**Comment by andrewrubin** [comment]
great idea @rvno 

I'll make a separate issue for that

**Comment by andrewrubin** [comment]
> _Think it'd be particularly useful to have a command that can include/exclude/omit which locales are being built as well._ 

Just an update there, that is being discussed with issue #56 , and has been fixed in v2.0.0 release (#65)

**Comment by andrewrubin** [comment]
Resurrecting this:
Creating new locales if they don't exist, when using the `--locales` flag while creating a Page.

I think it's still a cool idea, but there are some concerns:
- It needs to generate a `globals` file for the locale
- How does that globals file get generated — i.e. from what? The default language? A user-specified one after a prompt in the command line?

These feel like pretty opinionated decisions for a small return. Might just be easier to create a global locale file manuall. But I'm happy for us to go down this path though, let's chat about it

**Comment by andrewrubin** [comment]
Any opinions on my last comment there, a year later? 🙃 

Is this issue worth addressing? Should we just error/warn instead, if someone tried to bootstrap a page with a non-existent locale?

**Comment by marlonmarcello** [comment]
@andrewrubin I think giving a warning is a good idea. Instead of flags and options we could just make this a series of steps too like for example when you bootstrap the component library and it makes a few questions before generating a config.

**Comment by andrewrubin** [comment]
I've created an issue to add this warning, in #181 

Closing!
