### ISSUE TITLE
Cleanup `_app`

### ISSUE THREAD

**Issue by marlonmarcello** [wethegit/corgi#82]
We have a few unused and unnecessary things polluting `_app` at the moment:

1. `pageProps` is [spread into every](https://github.com/wethegit/corgi/blob/main/cli/templates/project/src/pages/_app.jsx#L12) element inside `_app` when we in fact just need it in the context
2. We have `AppStateProvider`, `PageProvider` and `LocaleProvider`. We don't need a `PageProvider`, we can get rid of it
3. We pass `version` from `package.json` around and we don't use it for anything, we should delete and remove all its deps

**Comment by andrewrubin** [comment]
Hey @marlonmarcello I am working on this one now :)

Admittedly, `PageProvider` served a larger purpose back when we had page transitions in place, so yeah I agree we can remove!

Currently it does serve the purpose of passing the proper locale folder slug down to `useLocale()`. Removing page provider does imply that we'll have to adjust our page templates to do something like:

```jsx
const HomePage = () => {
  useLocale("home") // this line, specifically, initializes the locale data

  return <h1>Some cool stuff</h1>
}
```


Just a heads-up. Or maybe there's another solution I haven't thought of yet.

**Comment by marlonmarcello** [comment]
@andrewrubin that should be part of `localeContext` I think.

**Comment by andrewrubin** [comment]
Right, I like that better. Thanks, updating the PR
