### ISSUE TITLE
Add "index" YAML settings; allow for "destructure" of data

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/corgi#92]
This issue contains two features:

1. Allow for `index.yml` files in `src/locales/globals` and _every_ `src/locales/[page]` directory. These index files would be _merged_ with every locale-specific YAML file. The idea here is to provide a way to specify global or page-specific data without it being repeated across every locale file.
2. Give developers the ability to "destructure" data from their `globals` or `page` YAML, if they specifically do not want to pull in everything. This could take the form of a function which includes or excludes specific keys, for example.

**Comment by ste-vg** [comment]
Would it be better if the data is returned separately to locale and global. so we don't get clashes and unexpected overwrites when we merge. Perhaps `globalData` and 'localeData`? Or maybe a separate `useData` hook?

**Comment by andrewrubin** [comment]
> Would it be better if the data is returned separately to locale and global. so we don't get clashes and unexpected overwrites when we merge. Perhaps `globalData` and `localeData` ? Or maybe a separate `useData` hook? 

Yes, 100%. That is what I meant to convey, but I was probably not very clear 🤣
